// Mock audit log entries — static array of recommendation state changes
export const mockAuditLog = [
  {
    id: "audit-001",
    timestamp: "2026-04-15T09:14:32Z",
    user: "Priya Sharma (RM)",
    action: "STATUS_CHANGE",
    resource: "Recommendation rec-001 — Franklin India ELSS Tax Saver",
    fromStatus: "PENDING",
    toStatus: "APPROVED",
    rationale: "Fund has completed lock-in. Low rating (2★) justifies full sell of unlocked units.",
  },
  {
    id: "audit-002",
    timestamp: "2026-04-15T09:22:10Z",
    user: "Priya Sharma (RM)",
    action: "STATUS_CHANGE",
    resource: "Recommendation rec-005 — Nippon India Large Cap Fund",
    fromStatus: "PENDING",
    toStatus: "L2_PENDING",
    rationale: "Amount exceeds ₹5L threshold — escalated to L2 for final sign-off.",
  },
  {
    id: "audit-003",
    timestamp: "2026-04-15T10:05:44Z",
    user: "Arvind Rao (L2)",
    action: "STATUS_CHANGE",
    resource: "Recommendation rec-005 — Nippon India Large Cap Fund",
    fromStatus: "L2_PENDING",
    toStatus: "APPROVED",
    rationale: "Buy aligned with mandate rebalancing target. Large Cap underweight confirmed.",
  },
  {
    id: "audit-004",
    timestamp: "2026-04-15T10:31:18Z",
    user: "Priya Sharma (RM)",
    action: "MODIFY",
    resource: "Recommendation rec-007 — HSBC Midcap Fund",
    fromStatus: "PENDING",
    toStatus: "PENDING",
    rationale: "Reduced buy amount from ₹2,80,000 to ₹2,10,000 due to client liquidity constraint.",
  },
  {
    id: "audit-005",
    timestamp: "2026-04-15T11:00:00Z",
    user: "System",
    action: "RECALCULATE",
    resource: "Portfolio — Rahul Mehta (5201745730863104)",
    fromStatus: "IN_PROGRESS",
    toStatus: "IN_PROGRESS",
    rationale: "Compliance re-check triggered after modification to rec-007. All allocations within mandate bands.",
  },
  {
    id: "audit-006",
    timestamp: "2026-04-15T11:45:02Z",
    user: "Priya Sharma (RM)",
    action: "STATUS_CHANGE",
    resource: "Recommendation rec-003 — Mirae Asset ELSS Tax Saver (DK3)",
    fromStatus: "PENDING",
    toStatus: "REJECTED",
    rationale: "Client requested to hold remaining ELSS units for tax optimisation in FY2026-27.",
  },
  {
    id: "audit-007",
    timestamp: "2026-04-15T12:10:55Z",
    user: "Arvind Rao (L2)",
    action: "STATUS_CHANGE",
    resource: "Recommendation rec-008 — BANDHAN Small Cap Fund",
    fromStatus: "L2_PENDING",
    toStatus: "APPROVED",
    rationale: "Small Cap underweight is 6.72%. Buy allocation restores portfolio within target band.",
  },
  {
    id: "audit-008",
    timestamp: "2026-04-15T13:00:00Z",
    user: "System",
    action: "BSE_EXPORT",
    resource: "BSE Order File — Batch #2026041501",
    fromStatus: "APPROVED",
    toStatus: "COMPLETED",
    rationale: "Order file generated and dispatched to BSE MFSS. 14 order lines included.",
  },
  {
    id: "audit-009",
    timestamp: "2026-04-14T15:22:30Z",
    user: "Priya Sharma (RM)",
    action: "STATUS_CHANGE",
    resource: "Recommendation rec-011 — Mirae Asset Large Cap Fund",
    fromStatus: "PENDING",
    toStatus: "APPROVED",
    rationale: "5★ large cap fund. Buy aligns with mandate target. No exit load concerns.",
  },
  {
    id: "audit-010",
    timestamp: "2026-04-14T16:05:12Z",
    user: "Priya Sharma (RM)",
    action: "STATUS_CHANGE",
    resource: "Portfolio — Surbhi Narain (5201745730001122)",
    fromStatus: "PENDING_REVIEW",
    toStatus: "IN_PROGRESS",
    rationale: "Started monthly review. Drift at 6.42% — exceeds 5% threshold.",
  },
  {
    id: "audit-011",
    timestamp: "2026-04-14T16:48:00Z",
    user: "Arvind Rao (L2)",
    action: "STATUS_CHANGE",
    resource: "Recommendation rec-002 — Mirae Asset ELSS Tax Saver (DM9)",
    fromStatus: "L2_PENDING",
    toStatus: "REJECTED",
    rationale: "Lock-in still active on 43% of holding. Defer sell to next review cycle.",
  },
  {
    id: "audit-012",
    timestamp: "2026-04-13T09:30:00Z",
    user: "System",
    action: "RECALCULATE",
    resource: "Portfolio — Vikram Nair (5201745730002233)",
    fromStatus: "PENDING_REVIEW",
    toStatus: "PENDING_REVIEW",
    rationale: "Scheduled drift computation. Current drift 7.44% — flagged P1.",
  },
  {
    id: "audit-013",
    timestamp: "2026-04-13T11:15:45Z",
    user: "Priya Sharma (RM)",
    action: "MODIFY",
    resource: "Recommendation rec-006 — Axis Long Term Equity ELSS",
    fromStatus: "PENDING",
    toStatus: "PENDING",
    rationale: "Increased sell amount by ₹50,000 to fully utilise LTCG exemption for FY2026-27.",
  },
  {
    id: "audit-014",
    timestamp: "2026-04-12T14:00:00Z",
    user: "System",
    action: "BSE_EXPORT",
    resource: "BSE Order File — Batch #2026041201",
    fromStatus: "APPROVED",
    toStatus: "COMPLETED",
    rationale: "Sell orders dispatched for Meera Banerjee portfolio. Settlement T+2.",
  },
  {
    id: "audit-015",
    timestamp: "2026-04-11T10:00:00Z",
    user: "Arvind Rao (L2)",
    action: "STATUS_CHANGE",
    resource: "Portfolio — Arjun Desai (5201745730006677)",
    fromStatus: "IN_PROGRESS",
    toStatus: "APPROVED",
    rationale: "All recommendations reviewed and compliant. Ready for BSE order export.",
  },
];
